# Generated by Django 3.2.7 on 2022-09-16 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amneties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('slug', models.SlugField(max_length=256)),
                ('image', models.ImageField(blank=True, null=True, upload_to='amneties')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Complimentary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('photos', models.ImageField(blank=True, null=True, upload_to='complimentary')),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('location', models.URLField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='hotel')),
                ('price', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('address', models.CharField(max_length=256)),
                ('phone_number', models.CharField(max_length=16)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='rooms')),
                ('price', models.IntegerField()),
                ('size', models.IntegerField()),
                ('amneties', models.ManyToManyField(to='hotel.Amneties')),
                ('compimentary', models.ManyToManyField(blank=True, default=None, to='hotel.Complimentary')),
                ('hotel', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotels')),
                ('room_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_type', to='hotel.category')),
            ],
        ),
        migrations.AddField(
            model_name='hotels',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.rooms'),
        ),
        migrations.CreateModel(
            name='HotelGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='hotel')),
                ('hotels', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotels')),
            ],
            options={
                'verbose_name': 'Hotel Gallery',
                'verbose_name_plural': 'Hotel Gallery',
            },
        ),
    ]
