# Generated by Django 3.2.7 on 2022-09-17 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotels',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hotel_room', to='hotel.rooms'),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='amneties',
            field=models.ManyToManyField(related_name='allamneties', to='hotel.Amneties'),
        ),
    ]
