# Generated by Django 3.2.7 on 2022-09-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20220917_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='rooms_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
