# Generated by Django 3.2.7 on 2022-09-18 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_category_rooms_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
