# Generated by Django 3.2.7 on 2022-09-20 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_rename_name_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelgallery',
            name='rooms',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='hotel.rooms'),
        ),
    ]
