# Generated by Django 3.2.7 on 2022-09-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_rooms_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
