# Generated by Django 3.2.7 on 2022-09-27 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_rooms_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
