# Generated by Django 3.2.7 on 2021-09-30 13:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.IntegerField()),
                ('description', models.TextField(blank=True, max_length=255)),
                ('agent_image', models.ImageField(blank=True, upload_to='photos/agents')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now_add=True)),
                ('discount', models.IntegerField()),
                ('is_available', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
            },
        ),
        migrations.CreateModel(
            name='Amneties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=200)),
                ('bustype', models.CharField(choices=[('AC', 'AC'), ('DELUXE', 'DELUXE'), ('NORMAL', 'NORMAL'), ('HIACE', 'HIACE'), ('JEEP', 'JEEP')], max_length=100)),
                ('bus_image', models.ImageField(blank=True, upload_to='photos/photo')),
                ('boarding_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration', models.IntegerField(blank=True)),
                ('discount', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('bus_number', models.CharField(max_length=100)),
                ('driver_name', models.CharField(max_length=100)),
                ('seat_type', models.CharField(choices=[('1*1', '1*1'), ('3*2', '3*2'), ('1*2', '1*2'), ('3*3', '3*3'), ('2*3', '2*3'), ('2*2', '2*2'), ('2*1', '2*1')], max_length=100)),
                ('no_seats', models.IntegerField(default=40)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('price', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('amneties', models.ManyToManyField(blank=True, to='bus.Amneties')),
            ],
        ),
        migrations.CreateModel(
            name='pickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_no', models.IntegerField()),
                ('occupant_firstname', models.CharField(max_length=200)),
                ('occupant_lastname', models.CharField(max_length=200)),
                ('occupant_email', models.EmailField(max_length=255)),
                ('purchase_time', models.DateTimeField(auto_now_add=True)),
                ('book_id', models.CharField(blank=True, max_length=250)),
                ('date_added', models.DateField(default=1)),
                ('bus', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bus.bus')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('start_point', models.CharField(blank=True, max_length=100)),
                ('end_point', models.CharField(blank=True, max_length=100)),
                ('distance', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('pickup_point', models.ManyToManyField(blank=True, to='bus.pickupPoint')),
            ],
        ),
        migrations.AddField(
            model_name='bus',
            name='booked_seat',
            field=models.ManyToManyField(blank=True, default=0, related_name='_bus_bus_booked_seat_+', to='bus.Seat'),
        ),
        migrations.AddField(
            model_name='bus',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.agent'),
        ),
        migrations.AddField(
            model_name='bus',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.route'),
        ),
        migrations.AddField(
            model_name='agent',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.route'),
        ),
    ]
