# Generated by Django 3.2.7 on 2021-09-20 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='slug',
        ),
    ]
