# Generated by Django 3.2.7 on 2021-09-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='booked_seat',
            field=models.ManyToManyField(blank=True, default=[0], related_name='_bus_bus_booked_seat_+', to='bus.Seat'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='seat_type',
            field=models.CharField(choices=[('3*3', '3*3'), ('2*1', '2*1'), ('2*2', '2*2'), ('1*1', '1*1'), ('2*3', '2*3'), ('3*2', '3*2'), ('1*2', '1*2')], max_length=100),
        ),
    ]
