# Generated by Django 3.2.7 on 2021-09-30 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_auto_20210930_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='seat',
            name='bookedseat_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bus',
            name='seat_type',
            field=models.CharField(choices=[('1*1', '1*1'), ('2*3', '2*3'), ('3*3', '3*3'), ('3*2', '3*2'), ('1*2', '1*2'), ('2*1', '2*1'), ('2*2', '2*2')], max_length=100),
        ),
    ]
