# Generated by Django 3.2.7 on 2021-09-26 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_auto_20210926_0727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='booked_seat',
        ),
        migrations.AddField(
            model_name='seat',
            name='bus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bus.bus'),
        ),
        migrations.AlterField(
            model_name='booking_seat',
            name='seat_no',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bus.seat'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='seat_type',
            field=models.CharField(choices=[('3*3', '3*3'), ('2*1', '2*1'), ('1*2', '1*2'), ('2*3', '2*3'), ('3*2', '3*2'), ('2*2', '2*2'), ('1*1', '1*1')], max_length=100),
        ),
    ]
