# Generated by Django 3.2.7 on 2021-09-26 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_auto_20210926_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='booked_seat',
            field=models.ManyToManyField(blank=True, default=1, to='bus.Booking_seat'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='seat_type',
            field=models.CharField(choices=[('3*3', '3*3'), ('2*1', '2*1'), ('1*1', '1*1'), ('2*3', '2*3'), ('1*2', '1*2'), ('2*2', '2*2'), ('3*2', '3*2')], max_length=100),
        ),
    ]
