# Generated by Django 3.2.7 on 2021-09-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0004_alter_bus_seat_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='bus_id',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='bus',
            name='seat_type',
            field=models.CharField(choices=[('2*1', '2*1'), ('2*2', '2*2'), ('2*3', '2*3'), ('1*1', '1*1'), ('3*2', '3*2'), ('3*3', '3*3'), ('1*2', '1*2')], max_length=100),
        ),
    ]
