# Generated by Django 3.2.7 on 2021-09-24 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0004_bus_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='routes',
            new_name='route',
        ),
    ]
