# Generated by Django 3.2.7 on 2021-09-24 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0005_rename_routes_agent_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='route',
            name='pickup_point',
        ),
        migrations.AddField(
            model_name='pickuppoint',
            name='route',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='bus.route'),
        ),
    ]
