# Generated by Django 3.2.7 on 2021-09-24 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0006_auto_20210924_0507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickuppoint',
            name='route',
        ),
    ]
