# Generated by Django 3.2.7 on 2022-09-20 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('bus', '0007_auto_20220920_2006'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seatdetail',
            old_name='Seat_no',
            new_name='seat_no',
        ),
        migrations.RemoveField(
            model_name='seatdetail',
            name='seat',
        ),
        migrations.AddField(
            model_name='seatdetail',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model_in': 'Seat'}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='seatdetail',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='seat_type',
            field=models.CharField(choices=[('3*2', '3*2'), ('1*2', '1*2'), ('2*1', '2*1'), ('2*3', '2*3'), ('3*3', '3*3'), ('1*1', '1*1'), ('2*2', '2*2')], max_length=100),
        ),
    ]
