# Generated by Django 3.2.7 on 2021-09-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0007_alter_bus_seat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='seat_type',
            field=models.CharField(choices=[('2*2', '2*2'), ('2*3', '2*3'), ('3*3', '3*3'), ('1*2', '1*2'), ('3*2', '3*2'), ('1*1', '1*1'), ('2*1', '2*1')], max_length=100),
        ),
        migrations.AlterField(
            model_name='seat',
            name='seat_no',
            field=models.IntegerField(default=40),
        ),
    ]
