# Generated by Django 3.2.7 on 2021-10-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0008_auto_20210930_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='seat_type',
            field=models.CharField(choices=[('3*2', '3*2'), ('3*3', '3*3'), ('2*2', '2*2'), ('2*1', '2*1'), ('1*2', '1*2'), ('1*1', '1*1'), ('2*3', '2*3')], max_length=100),
        ),
        migrations.AlterField(
            model_name='seat',
            name='bookedseat_no',
            field=models.IntegerField(),
        ),
    ]
