# Generated by Django 3.2.7 on 2021-09-24 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0008_pickuppoint_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickuppoint',
            name='route',
        ),
        migrations.AddField(
            model_name='pickuppoint',
            name='route',
            field=models.ManyToManyField(to='bus.Route'),
        ),
    ]
