# Generated by Django 3.2.7 on 2021-09-24 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0009_auto_20210924_0514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bus',
            old_name='route_name',
            new_name='route',
        ),
    ]
