# Generated by Django 3.2.7 on 2021-09-24 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0010_rename_route_name_bus_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickuppoint',
            name='route',
        ),
        migrations.AddField(
            model_name='route',
            name='pickup_point',
            field=models.ManyToManyField(blank=True, to='bus.pickupPoint'),
        ),
    ]
