# Generated by Django 3.2.7 on 2022-09-20 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('bus', '0010_auto_20220920_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='seat_type',
            field=models.CharField(choices=[('2*2', '2*2'), ('2*3', '2*3'), ('1*2', '1*2'), ('1*1', '1*1'), ('3*2', '3*2'), ('3*3', '3*3'), ('2*1', '2*1')], max_length=100),
        ),
        migrations.AlterField(
            model_name='seatdetail',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
