# Generated by Django 3.2.7 on 2021-09-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0011_auto_20210924_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='seat_type',
            field=models.CharField(choices=[('3*3', '3*3'), ('1*2', '1*2'), ('2*1', '2*1'), ('2*2', '2*2'), ('1*1', '1*1'), ('2*3', '2*3'), ('3*2', '3*2')], default=1, max_length=100),
        ),
    ]
