# Generated by Django 3.2.7 on 2022-09-21 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0012_auto_20220921_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='rating',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='seatdetail',
            name='last_seat_no',
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='bus',
            name='seat_type',
            field=models.CharField(choices=[('2*2', '2*2'), ('3*2', '3*2'), ('1*2', '1*2'), ('2*1', '2*1'), ('1*1', '1*1'), ('2*3', '2*3'), ('3*3', '3*3')], max_length=100),
        ),
    ]
