# Generated by Django 3.2.7 on 2021-09-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0012_bus_seat_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='seat_type',
            field=models.CharField(choices=[('2*1', '2*1'), ('3*3', '3*3'), ('1*1', '1*1'), ('2*2', '2*2'), ('2*3', '2*3'), ('1*2', '1*2'), ('3*2', '3*2')], default=1, max_length=100),
        ),
    ]
