# Generated by Django 3.2.7 on 2022-09-21 03:26

import bus.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0013_auto_20220921_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='seat_type',
            field=models.CharField(choices=[('2*2', '2*2'), ('2*3', '2*3'), ('1*2', '1*2'), ('1*1', '1*1'), ('3*3', '3*3'), ('2*1', '2*1'), ('3*2', '3*2')], max_length=100),
        ),
        migrations.AlterField(
            model_name='seat',
            name='bookedseat_no',
            field=models.IntegerField(blank=True, null=True, validators=[bus.models.seat_check]),
        ),
    ]
